# This file configures Trivy.

format: sarif
output: trivy-results.sarif
exit-code: 1
severity: CRITICAL,HIGH,MEDIUM,LOW
images:
- node-image:v1
paths:
- ./
secrets:
- /[a-zA-Z0-9]{8,}/
- /[a-zA-Z0-9]{32,}/
secret_types:
- password
- api_key
- secret_key
- token


ignore-unfixed: false
skip-update: false
skip-refresh: false
timeout: 300
debug: true
